### PR TITLE
Implements IAsyncParseNodeFactory interface

### PR DESCRIPTION
**Pull request by MihaMarkic**

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Thanks for starting this PR, it needs:
- version bump (patch)
- changelog entry (patch, tomorrow, changed)
- updated reference to abstractions

**Review by baywet — APPROVED** [review]
@MihaMarkic is this good to merge from your perspective?

**Comment by MihaMarkic** [comment]
@baywet Added ConfigureAwait, now it's good.

**Review by andrueastman — APPROVED** [review]
Thanks for the contribution here

**Pull request merged**
